{"errorMessage": "An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: Subject", "errorType": "InvalidParameterException", "stackTrace": [["/var/task/lambda_function.py", 73, "lambda_handler", "row_count = processContentAndSave(table, content)"], ["/var/task/lambda_function.py", 116, "processContentAndSave", "MessageStructure='json'"], ["/var/runtime/botocore/client.py", 314, "_api_call", "return self._make_api_call(operation_name, kwargs)"], ["/var/runtime/botocore/client.py", 612, "_make_api_call", "raise error_class(parsed_response, operation_name)"]]}